### ISSUE TITLE
About Cost Volumes Visualization

### ISSUE THREAD

**Issue by DQiaole** [xiaofeng94/GMFlowNet#8]
Hi~
Thank you very much for your great work! 
I have some questions about the cost volume visualization. As you state in the appendix, the cost volume are visualized after softmax, but I find there are some values which are greater than 1 in Fig. 10(a) as follows. I'm confused about this.  Besides, if you could upload the code for the visualization, I could appreciate it.
Thanks in advance.
![image](https://user-images.githubusercontent.com/49903017/195306672-728e38d3-5286-42bd-b87c-fb4d90a841d2.png)

**Comment by xiaofeng94** [comment]
Hey, I cannot recall all the details but there should be some scaling to make the visualization better. @zhang-zx may provide more details for you.

**Comment by zhang-zx** [comment]
Thanks for your interest in our work. About the visualization, we loaded the cost volume data, calculated the absolute value of the data times a normalization factor, and then calculated the sqrt value to get the final visualization result. This is because the peak value of the cost volume is so significant that it covers the variance of values elsewhere.

**Comment by DQiaole** [comment]
Thanks to the replies from both authors, I got a similar shape after trying. And I'll close this issue.

**Comment by xiewende** [comment]
@DQiaole Could you provide the code for cost volumes visualization, i can‘t get the similar shape
